import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;

/**
 * Standalone tool — sinh BCrypt hash cho các tài khoản demo và in ra câu SQL UPDATE.
 *
 * Chạy:
 *   cd D:\PROJECTS_VANH\itam-system\backend
 *   .\hash-password.ps1
 */
public class HashPassword {

    public static void main(String[] args) {
        BCryptPasswordEncoder encoder = new BCryptPasswordEncoder(10);

        // Danh sách email → password cần hash
        String[][] accounts = {
            { "admin@itam.local",      "Admin@123456"  },
            { "it.staff@itam.local",   "Itstaff@123"   },
            { "manager.kd@itam.local", "Manager@123"   },
            { "manager.hc@itam.local", "Manager@123"   },
            { "employee1@itam.local",  "Employee@123"  },
            { "employee2@itam.local",  "Employee@123"  },
        };

        System.out.println("-- ============================================================");
        System.out.println("-- SQL UPDATE password_hash cho database itam_dev");
        System.out.println("-- Generated by HashPassword.java");
        System.out.println("-- ============================================================");
        System.out.println();

        for (String[] account : accounts) {
            String email    = account[0];
            String password = account[1];
            String hash     = encoder.encode(password);

            System.out.printf(
                "UPDATE employees SET password_hash = '%s' WHERE email = '%s'; -- %s%n",
                hash, email, password
            );
        }

        System.out.println();
        System.out.println("-- Verify: chạy lại tool và kiểm tra output, mỗi lần hash sẽ khác nhau");
        System.out.println("-- nhưng đều match với password gốc (BCrypt salt ngẫu nhiên).");
    }
}
